# Generated by Django 5.1.3 on 2025-01-10 03:01

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import guide.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20, verbose_name='カテゴリ名')),
            ],
            options={
                'verbose_name_plural': 'カテゴリ名',
            },
        ),
        migrations.CreateModel(
            name='Information_pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.CharField(max_length=700, verbose_name='説明')),
                ('address', models.CharField(max_length=50, verbose_name='住所')),
            ],
            options={
                'verbose_name_plural': '説明',
            },
        ),
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_name', models.CharField(max_length=10, verbose_name='種類名')),
            ],
            options={
                'verbose_name_plural': '種類',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('number', models.BigIntegerField(default=guide.models.random_num, primary_key=True, serialize=False, verbose_name='社員番号')),
                ('name', models.CharField(max_length=20, verbose_name='氏名')),
                ('password', models.CharField(max_length=256, verbose_name='パスワード')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('admin', models.BooleanField(default=False, verbose_name='管理者')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'カスタムユーザー',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_number', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='事例番号')),
                ('title', models.CharField(max_length=30, verbose_name='タイトル')),
                ('category', models.IntegerField(verbose_name='カテゴリ')),
                ('main', models.CharField(max_length=300, verbose_name='本文')),
                ('post_date', models.DateTimeField(max_length=20, verbose_name='投稿日')),
                ('authonrization', models.BooleanField(default=False, max_length=20, verbose_name='認可済')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='社員番号')),
            ],
            options={
                'verbose_name_plural': '事例',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500, verbose_name='コメント')),
                ('case_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.case', verbose_name='事例番号')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='社員番号')),
            ],
            options={
                'verbose_name_plural': 'コメント',
            },
        ),
        migrations.CreateModel(
            name='GuidePin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(verbose_name='種類')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='社員番号')),
            ],
            options={
                'verbose_name_plural': '社員番号',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=50, verbose_name='ツアー名')),
                ('location', models.CharField(max_length=4, verbose_name='場所')),
                ('tour_date', models.DateTimeField(verbose_name='ツアー日')),
                ('information_pin', models.IntegerField(verbose_name='案内ピン')),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='社員番号')),
            ],
            options={
                'verbose_name_plural': 'ツアー',
            },
        ),
    ]
