# Generated by Django 5.1.3 on 2025-01-10 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_alter_guidepin_options_guidepin_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidepin',
            name='sort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.sort', verbose_name='種類'),
        ),
    ]
