# Generated by Django 5.1.3 on 2025-01-10 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_alter_guidepin_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.category', verbose_name='カテゴリ'),
        ),
    ]
