# Generated by Django 5.1.3 on 2025-01-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0005_alter_case_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='information_pin',
            name='place',
            field=models.CharField(default='unknown', max_length=30, verbose_name='場所'),
        ),
    ]
