# Generated by Django 5.1.3 on 2025-01-15 05:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0006_information_pin_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='post_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='投稿日'),
        ),
    ]
