# Generated by Django 5.1.3 on 2025-01-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0008_alter_customuser_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information_pin',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='information_pin',
        ),
        migrations.AddField(
            model_name='information_pin',
            name='information_pin_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='案内ピン番号'),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_number',
            field=models.CharField(default='00000000', max_length=8, primary_key=True, serialize=False, verbose_name='ツアー番号'),
        ),
    ]
