# Generated by Django 5.1.3 on 2025-01-22 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0009_remove_information_pin_id_remove_tour_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='information_pin',
            name='tour',
            field=models.ForeignKey(default='00000000', on_delete=django.db.models.deletion.CASCADE, related_name='information_pin', to='guide.tour', verbose_name='ツアー番号'),
            preserve_default=False,
        ),
    ]
