# Generated by Django 5.1.3 on 2025-01-22 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0010_information_pin_tour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information_pin',
            old_name='tour',
            new_name='tour_number',
        ),
    ]
