# Generated by Django 5.1.3 on 2025-01-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0011_rename_tour_information_pin_tour_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='information_pin',
            name='tour_name',
            field=models.CharField(default='ツアー名入れる場所', max_length=30, verbose_name='ツアー名'),
            preserve_default=False,
        ),
    ]
