# Generated by Django 5.1.3 on 2025-01-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0012_information_pin_tour_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information_pin',
            name='place',
        ),
        migrations.AddField(
            model_name='information_pin',
            name='pref',
            field=models.CharField(default='unknown', max_length=30, verbose_name='都道府県'),
        ),
    ]
