# Generated by Django 5.1.3 on 2025-01-27 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0013_remove_information_pin_place_information_pin_pref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information_pin',
            name='pref',
        ),
        migrations.RemoveField(
            model_name='information_pin',
            name='tour_name',
        ),
        migrations.AddField(
            model_name='information_pin',
            name='place',
            field=models.CharField(default='unknown', max_length=30, verbose_name='場所'),
        ),
    ]
