# Generated by Django 5.1.3 on 2025-01-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0015_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='information_pin',
            name='image',
            field=models.ImageField(blank=True, default='images/no_image.png', upload_to='images/', verbose_name='画像'),
        ),
    ]
