# Generated by Django 5.1.3 on 2025-02-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0016_information_pin_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='authonrization',
            new_name='authorization',
        ),
        migrations.RemoveField(
            model_name='information_pin',
            name='information_pin_id',
        ),
        migrations.AddField(
            model_name='information_pin',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
